/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.Medicinetype.Medicine;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SellingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Rohan
 */
public class PatientAnalysisJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PatientOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;

    /**
     * Creates new form FarmerAnalysisJPanel
     */
    public PatientAnalysisJPanel(JPanel userProcessContainer, UserAccount account,
            PatientOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = account;
      
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewWorkRequestBtn = new javax.swing.JButton();

        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewWorkRequestBtn.setBackground(new java.awt.Color(255, 204, 0));
        ViewWorkRequestBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ViewWorkRequestBtn.setText("Work Request ");
        ViewWorkRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewWorkRequestBtnActionPerformed(evt);
            }
        });
        add(ViewWorkRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 600, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewWorkRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewWorkRequestBtnActionPerformed
        // TODO add your handling code here:
        PatientWorkAreaJPanel farmerWorkAreaJPanel1 = new PatientWorkAreaJPanel(userProcessContainer, userAccount, (PatientOrganization) organization, enterprise, business);
        userProcessContainer.add("farmerWorkAreaJPanel1", farmerWorkAreaJPanel1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_ViewWorkRequestBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewWorkRequestBtn;
    // End of variables declaration//GEN-END:variables
}
