/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HealthCampsEnterprise;
import Business.Network.Network;
import Business.Organization.HealthCampsOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarrierWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rohan
 */
public class RequestServiceProviderJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form RequestServiceProviderJPanel
     */
    public RequestServiceProviderJPanel(JPanel userProcessContainer, UserAccount account,
            Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(enterprise.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        txtPlanCost = new javax.swing.JTextField();
        lblTypeOfProvider = new javax.swing.JLabel();
        lblPlanType = new javax.swing.JLabel();
        lblPlanCost = new javax.swing.JLabel();
        cmbTypeOfProvider = new javax.swing.JComboBox<String>();
        cmbTypeOfPlan = new javax.swing.JComboBox<String>();
        backJButton = new javax.swing.JButton();
        btnRequestService = new javax.swing.JButton();
        btnCheckCost = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setText("ENTERPRISE:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 91, 60, 30));

        txtPlanCost.setEditable(false);
        txtPlanCost.setEnabled(false);
        txtPlanCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlanCostActionPerformed(evt);
            }
        });
        add(txtPlanCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 200, 30));

        lblTypeOfProvider.setText("1. TYPE OF PROVIDER:");
        add(lblTypeOfProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        lblPlanType.setText("2. TYPE OF SERVICE:");
        add(lblPlanType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 170, -1));

        lblPlanCost.setText("3. COST: ");
        add(lblPlanCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 100, -1));

        cmbTypeOfProvider.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UCI Health", "American College of Physicians", "Primary Care" }));
        cmbTypeOfProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeOfProviderActionPerformed(evt);
            }
        });
        add(cmbTypeOfProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 200, 40));

        cmbTypeOfPlan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Psychological Services", "Flu shot", "Physical Examination", "" }));
        cmbTypeOfPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeOfPlanActionPerformed(evt);
            }
        });
        add(cmbTypeOfPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 200, -1));

        backJButton.setBackground(new java.awt.Color(255, 204, 0));
        backJButton.setText("<< BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 129, -1));

        btnRequestService.setBackground(new java.awt.Color(255, 204, 0));
        btnRequestService.setText("REQUEST SERVICE");
        btnRequestService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestServiceActionPerformed(evt);
            }
        });
        add(btnRequestService, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        btnCheckCost.setBackground(new java.awt.Color(255, 204, 0));
        btnCheckCost.setText("CLICK TO CHECK PRICE");
        btnCheckCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckCostActionPerformed(evt);
            }
        });
        add(btnCheckCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("REQUEST MEDICAL SERVICE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Patient/health.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkAreaJPanel dwjp = (PatientWorkAreaJPanel) component;
        dwjp.populateServiceRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnRequestServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestServiceActionPerformed
        // TODO add your handling code here:
        if (txtPlanCost.getText() != null && !txtPlanCost.getText().isEmpty()) {
            String typeOfProvider = cmbTypeOfProvider.getSelectedItem().toString();
            String typeOfPlan = cmbTypeOfPlan.getSelectedItem().toString();
            CarrierWorkRequest carrierWorkRequest = new CarrierWorkRequest();
            carrierWorkRequest.setTypeOfProvider(typeOfProvider);
            carrierWorkRequest.setTypeOfPlan(typeOfPlan);
            // SelectPlan(typeOfProvider, typeOfPlan);
            carrierWorkRequest.setSender(userAccount);
            carrierWorkRequest.setStatus("Sent");
            carrierWorkRequest.setCost(Integer.parseInt(txtPlanCost.getText()));

            Organization org = null;
            for (Network network : business.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof HealthCampsEnterprise) {
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (organization instanceof HealthCampsOrganization) {
                                org = organization;
                                break;
                            }
                        }
                    }

                }
            }

            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(carrierWorkRequest);
                userAccount.getWorkQueue().getWorkRequestList().add(carrierWorkRequest);
            }
        JOptionPane.showMessageDialog(null, "Request created Successfully");
        //JOptionPane.showMessageDialog(null, "Request created Successfully", "Warning", JOptionPane.WARNING_MESSAGE);
        txtPlanCost.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a plan and  check the cost");
        }
    }//GEN-LAST:event_btnRequestServiceActionPerformed

    private void cmbTypeOfProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeOfProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeOfProviderActionPerformed

    private void btnCheckCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckCostActionPerformed
        // TODO add your handling code here:
        String typeOfProvider = cmbTypeOfProvider.getSelectedItem().toString();
        String typeOfPlan = cmbTypeOfPlan.getSelectedItem().toString();
        SelectPlan(typeOfProvider, typeOfPlan);
    }//GEN-LAST:event_btnCheckCostActionPerformed

    private void txtPlanCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlanCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlanCostActionPerformed

    private void cmbTypeOfPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeOfPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeOfPlanActionPerformed


    private void SelectPlan(String typeOfProvider, String typeOfPlan) {
        if (typeOfProvider.equals("UCI Health") && typeOfPlan.equals("Psychological Services")) {
            txtPlanCost.setText("100");
        } else if (typeOfProvider.equals("UCI Health") && typeOfPlan.equals("Flu shot")) {
            txtPlanCost.setText("20");
        } else if (typeOfProvider.equals("UCI Health") && typeOfPlan.equals("Physical Examination")) {
            txtPlanCost.setText("50");
        }
        if (typeOfProvider.equals("American College of Physicians") && typeOfPlan.equals("Psychological Services")) {
            txtPlanCost.setText("80");
        } else if (typeOfProvider.equals("American College of Physicians") && typeOfPlan.equals("Flu shot")) {
            txtPlanCost.setText("30");
        } else if (typeOfProvider.equals("American College of Physicians") && typeOfPlan.equals("Physical Examination")) {
            txtPlanCost.setText("60");
        }
        if (typeOfProvider.equals("Primary Care") && typeOfPlan.equals("Psychological Services")) {
            txtPlanCost.setText("70");
        } else if (typeOfProvider.equals("Primary Care") && typeOfPlan.equals("Flu shot")) {
            txtPlanCost.setText("30");
        } else if (typeOfProvider.equals("Primary Care") && typeOfPlan.equals("Physical Examination")) {
            txtPlanCost.setText("90");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnCheckCost;
    private javax.swing.JButton btnRequestService;
    private javax.swing.JComboBox<String> cmbTypeOfPlan;
    private javax.swing.JComboBox<String> cmbTypeOfProvider;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblPlanCost;
    private javax.swing.JLabel lblPlanType;
    private javax.swing.JLabel lblTypeOfProvider;
    private javax.swing.JTextField txtPlanCost;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
