/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FundingEnterprise;
import Business.Network.Network;
import Business.Organization.BankingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InterestFreeLoanWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.TrayIcon;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Rohan
 */
public class RequestInterestFreeLoanJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    ImageIcon picture;

    /**
     * Creates new form RequestInterestFreeLoanJPanel
     */
    public RequestInterestFreeLoanJPanel(JPanel userProcessContainer, UserAccount account,
            Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        // valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radioYes = new javax.swing.JRadioButton();
        radioNo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cmbIncome = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        chkCurrentIncome = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtloan = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        attachImagebtn = new javax.swing.JButton();
        imageDisplayLabel = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        attachImagebtn1 = new javax.swing.JButton();
        fileNameTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("PATIENT FINANCIAL APPLICATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 350, -1));

        lblName.setText("1. NAME :");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblAge.setText("2. AGE:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        lblGender.setText("3. GENDER:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        lblAddress.setText("4. ADDRESS:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel6.setText("6. HAVE YOU APPLIED FOR A LOAN, RECIEVED A LOAN OR COSIGNED ON A LOAN WITH THE FREE LOAN ASSOCIATION IN THE PAST ?*");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 780, -1));

        buttonGroup1.add(radioYes);
        radioYes.setText("Yes");
        add(radioYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        buttonGroup1.add(radioNo);
        radioNo.setText("No");
        add(radioNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jLabel7.setText("7. HOW MUCH IS YOUR MONTHLY INCOME ? *");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 270, -1));

        cmbIncome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Above 20000", "Between 15000 and 20000", "Below 10000" }));
        add(cmbIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jLabel8.setText("8. PLEASE PROVIDE INCOME DOCUMENT PROOF ? * ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 440, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 170, -1));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 170, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        chkCurrentIncome.setText("Proof of Current Income");
        add(chkCurrentIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 280, -1));

        btnSubmit.setBackground(new java.awt.Color(255, 204, 0));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 120, 25));

        jLabel9.setText("5. LOAN AMOUNT *");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, -1));
        add(txtloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 150, 30));

        btnBack.setBackground(new java.awt.Color(255, 204, 0));
        btnBack.setText("<< BACK ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 624, 120, 30));

        attachImagebtn.setText("Browse");
        attachImagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachImagebtnActionPerformed(evt);
            }
        });
        add(attachImagebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 80, 30));
        add(imageDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 250, 150));

        fileNameTextField.setEditable(false);
        add(fileNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 170, 30));

        attachImagebtn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        attachImagebtn1.setText("Browse");
        attachImagebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachImagebtn1ActionPerformed(evt);
            }
        });
        add(attachImagebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 80, 30));

        fileNameTextField2.setEditable(false);
        add(fileNameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 170, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Patient/medicalloan.jpeg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (!txtName.getText().isEmpty() && txtName.getText() != null
                && !txtAge.getText().isEmpty() && txtAge.getText() != null
                && !txtloan.getText().isEmpty() && txtloan.getText() != null
                && cmbIncome.getSelectedItem() != null
                &&  chkCurrentIncome.isSelected()) {

            if (!radioNo.isSelected() && !radioYes.isSelected()) {
                JOptionPane.showMessageDialog(null, "Please select the loan received with Free association");

            } else {
                AddRequest();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter values for empty field");
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkAreaJPanel dwjp = (PatientWorkAreaJPanel) component;
        dwjp.populateInterestFreeLoanRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void attachImagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachImagebtnActionPerformed
        // TODO add your handling code here:
        JFileChooser attachFile = new JFileChooser();
        // attachFile.setFileFilter(new FileNameExtensionFilter("Ima".jpg"));
        attachFile.showOpenDialog(null);
        File filePath = attachFile.getSelectedFile();
        if (filePath != null) {
            try {
                Image image = ImageIO.read(filePath);
                if (image != null) {
                    image = image.getScaledInstance(250, 140, java.awt.Image.SCALE_SMOOTH);
                    picture = new ImageIcon(image);
                    imageDisplayLabel.setIcon(picture);
                    String fileAbsolutePath = filePath.getAbsolutePath();
                    if (fileAbsolutePath != null) {
                        String fileName = fileAbsolutePath.substring(fileAbsolutePath.lastIndexOf("\\") + 1);
                        fileNameTextField.setText(fileName);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please select an image", "", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Image could not be set successfully");
            }
        }

    }//GEN-LAST:event_attachImagebtnActionPerformed

    private void attachImagebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachImagebtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attachImagebtn1ActionPerformed

    private void refreshForm() {
        txtName.setText("");
        txtAddress.setText("");
        txtAge.setText("");
        txtName.setText("");
        txtloan.setText("");
        txtGender.setText("");
        radioNo.setSelected(true);
        
        chkCurrentIncome.setSelected(false);
        
        cmbIncome.setSelectedIndex(0);
        fileNameTextField.setText("");
        imageDisplayLabel.setIcon(null);
    }

    private void AddRequest() {
        try {
            int age = 0;
            int loanAmount = 0;
            String name = txtName.getText();
            String gender = txtGender.getText();
            String address = txtAddress.getText();
            String monthlyIncome = cmbIncome.getSelectedItem().toString();

            age = Integer.parseInt(txtAge.getText());
            loanAmount = Integer.parseInt(txtloan.getText());

            InterestFreeLoanWorkRequest interestFreeLoanWorkRequest = new InterestFreeLoanWorkRequest();
            interestFreeLoanWorkRequest.setName(name);
            interestFreeLoanWorkRequest.setAge(age);
            interestFreeLoanWorkRequest.setAddress(address);
            interestFreeLoanWorkRequest.setAmount(loanAmount);
            interestFreeLoanWorkRequest.setGender(gender);
            interestFreeLoanWorkRequest.setMonthlyIncome(monthlyIncome);
            interestFreeLoanWorkRequest.setImage(picture);
            if (radioYes.isSelected()) {
                interestFreeLoanWorkRequest.setIsLoanApplied(true);
            } else {
                interestFreeLoanWorkRequest.setIsLoanApplied(false);
            }

            

            if (chkCurrentIncome.isSelected()) {
                interestFreeLoanWorkRequest.setIsCurrentIncome(true);
            } else {
                interestFreeLoanWorkRequest.setIsCurrentIncome(false);
            }
            interestFreeLoanWorkRequest.setSender(userAccount);
            interestFreeLoanWorkRequest.setStatus("Sent");

            Organization org = null;
            for (Network network : business.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof FundingEnterprise) {
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (organization instanceof BankingOrganization) {
                                org = organization;
                                break;
                            }
                        }
                    }

                }
            }

            if (org != null) {

                if (!org.getWorkQueue().getWorkRequestList().contains(interestFreeLoanWorkRequest)
                        && !interestFreeLoanWorkRequest.getIsLoanApplied()) {
                    org.getWorkQueue().getWorkRequestList().add(interestFreeLoanWorkRequest);
                    userAccount.getWorkQueue().getWorkRequestList().add(interestFreeLoanWorkRequest);
                    JOptionPane.showMessageDialog(null, "Your request has been added successfully");
                    refreshForm();
                } else {
                    JOptionPane.showMessageDialog(null, "Your request cannot be processed at the moment as you have already applied for it before.Kindly visit the nearest bank for the help");
                    refreshForm();
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter age and loan amount in integer");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachImagebtn;
    private javax.swing.JButton attachImagebtn1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkCurrentIncome;
    private javax.swing.JComboBox<String> cmbIncome;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JTextField fileNameTextField2;
    private javax.swing.JLabel imageDisplayLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioYes;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtloan;
    // End of variables declaration//GEN-END:variables
}
