/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.Medicinetype.Medicine;
import Business.Medicinetype.Medicine.MedicineType;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.DeliveryEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.DeliveryOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SellingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rohan
 */
public class RequestMedicineJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form RequestSellingJPanel
     */
    public RequestMedicineJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        populateComboBox();
    }
    private void populateComboBox() {
        cropJComboBox.removeAllItems();
        for (MedicineType Medicine : MedicineType.values()) {
            cropJComboBox.addItem(Medicine);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sourceTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        cropJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("1. Store : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel2.setText("2. Address:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLabel4.setText("4. Medicine Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
        add(sourceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 190, 30));
        add(destinationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 190, 30));

        createBtn.setBackground(new java.awt.Color(255, 204, 0));
        createBtn.setText("SUBMIT");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 190, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("REQUEST MEDICINE DELIVERY PORTAL");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        backBtn.setBackground(new java.awt.Color(255, 204, 0));
        backBtn.setText("<< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel6.setText("5. Quantity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));
        add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 190, 30));

        cropJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cropJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropJComboBoxActionPerformed(evt);
            }
        });
        add(cropJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Patient/medecine.jpeg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 316, 330, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;
        String source = sourceTextField.getText();
        boolean issourceValid = validateStrings(source);
        String destination = destinationTextField.getText();
        boolean isdestinationValid = validateStrings(destination);
       // String noOfTrucks = noOfTrucksTextField.getText();
       
        
//        try {
//            trucks = Integer.parseInt(noOfTrucks);
//        } catch (NumberFormatException e) {
//            isValid = false;
//            JOptionPane.showMessageDialog(null, "Enter valid number of trucks", "Error", JOptionPane.ERROR_MESSAGE);
//            throw e;
//        }
        String productName = (String)cropJComboBox.getSelectedItem().toString();
        boolean isproductNameValid = validateStrings(productName);
        //String qty = quantityTextField.getText();      
        int q;
         try {
            q =  Integer.parseInt(quantityTextField.getText());
        } catch (java.lang.NumberFormatException e) {
            isValid = false;
            JOptionPane.showMessageDialog(null, "Enter valid Quantity", "Error", JOptionPane.ERROR_MESSAGE);
            //throw e;
        }
       
//         int trucks=0;
//        if (isValid) {
//            if (q >= 500 && q <= 1000) {
//                trucks = 1;
//            } else if (q > 1000 && q <= 2000) {
//                trucks = 2;
//            } else if (q > 2000 && q <= 3000) {
//                trucks = 3;
//            } else if (q > 3000 && q <= 4000) {
//                trucks = 4;
//            } else if (q > 4000 && q <= 5000) {
//                trucks = 5;
//            }
//          
//        }
        if(isValid && issourceValid && isdestinationValid && isproductNameValid) {
        SellingWorkRequest sellingWorkRequest = new SellingWorkRequest();
        sellingWorkRequest.setSource(source);
        sellingWorkRequest.setDestination(destination);
        sellingWorkRequest.setNoOfTrucks(0);
        sellingWorkRequest.setProductName(productName);
        sellingWorkRequest.setQuantity(Integer.parseInt(quantityTextField.getText()));
        sellingWorkRequest.setSender(userAccount);
        sellingWorkRequest.setStatus("Process");

        Organization org = null;
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof DeliveryEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof DeliveryOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }

            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(sellingWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(sellingWorkRequest);
        }
        JOptionPane.showMessageDialog(null, "Request Created Sucessfully");
        //createBtn.setEnabled(false);
        sourceTextField.setText("");
        destinationTextField.setText("");
        quantityTextField.setText("");
      
        //cropJComboBox.removeAllItems();
        }
    }//GEN-LAST:event_createBtnActionPerformed
 public boolean validateStrings(String name){
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter mandatory value", "Error", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        Pattern pattern = Pattern.compile("[a-zA-Z ]*");
        Matcher matcher = pattern.matcher(name);
         if (!matcher.matches()) {
             
            JOptionPane.showMessageDialog(null, "Please Enter valid string value", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
      }
        return true;
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkAreaJPanel dwjp = (PatientWorkAreaJPanel) component;
        dwjp.populateSellingRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void cropJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropJComboBoxActionPerformed
      
    }//GEN-LAST:event_cropJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JComboBox cropJComboBox;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTextField sourceTextField;
    // End of variables declaration//GEN-END:variables
}
