/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;

import Business.Medicine.Medicine;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorTreatmentWorkRequest;
import Business.WorkQueue.MedicineSupplierWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rakesh
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    DoctorTreatmentWorkRequest docrequest;
    private UserAccount userAccount;
    private EcoSystem business;
    private Enterprise enterprise;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, UserAccount account, DoctorTreatmentWorkRequest docrequest, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.docrequest = docrequest;
        //  this.medicineOrganization = medicineOrganization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;



    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        commentsTextFiled = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resultJTextField1 = new javax.swing.JTextField();
        freemedicineTextField1 = new javax.swing.JTextField();
        QuantityTextfield1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nextTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setBackground(new java.awt.Color(255, 204, 0));
        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitJButton.setText("SUBMIT ");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 130, -1));

        jLabel1.setText("RESULT :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        add(commentsTextFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 192, -1));

        backJButton.setBackground(new java.awt.Color(255, 204, 0));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton.setText("<< BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("PATIENT EXAMINATION RESULT");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabel3.setText("MEDICINE : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel4.setText("OTHER COMMENTS :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel5.setText("QUANTITY: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));
        add(resultJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 192, -1));
        add(freemedicineTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 192, -1));
        add(QuantityTextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 192, -1));

        jLabel6.setText("NEXT APPOINTMENT DATE:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));
        add(nextTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 192, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Doctor/doctor1.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 370, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        //DoctorTreatmentWorkRequest request1 = new DoctorTreatmentWorkRequest();
        if ((!resultJTextField1.getText().equals("")) && (!freemedicineTextField1.getText().equals(""))
                && (!QuantityTextfield1.getText().equals("")) && (!nextTextField1.getText().equals(""))
                && (!commentsTextFiled.getText().equals(""))) {
            boolean isError = false;
            try {

                docrequest.setTestResult(resultJTextField1.getText());
                docrequest.setFreeMed(freemedicineTextField1.getText());
                docrequest.setQuantity(Integer.parseInt(QuantityTextfield1.getText()));
                docrequest.setAppointmentDate(nextTextField1.getText());
                docrequest.setComments(commentsTextFiled.getText());

                docrequest.setStatus("Completed"); //before
                JOptionPane.showMessageDialog(null, "You have successfully treated the patient !", "Information", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e3) {
                isError = true;
                JOptionPane.showMessageDialog(null, "Please input the details in proper format", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fill all the fields before submitting ", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QuantityTextfield1;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField commentsTextFiled;
    private javax.swing.JTextField freemedicineTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nextTextField1;
    private javax.swing.JTextField resultJTextField1;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
